
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CustomScoreTemplate` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CustomScoreTemplate
 * 
 */
export type CustomScoreTemplateModel = runtime.Types.Result.DefaultSelection<Prisma.$CustomScoreTemplatePayload>

export type AggregateCustomScoreTemplate = {
  _count: CustomScoreTemplateCountAggregateOutputType | null
  _min: CustomScoreTemplateMinAggregateOutputType | null
  _max: CustomScoreTemplateMaxAggregateOutputType | null
}

export type CustomScoreTemplateMinAggregateOutputType = {
  id: string | null
  gameId: string | null
  name: string | null
}

export type CustomScoreTemplateMaxAggregateOutputType = {
  id: string | null
  gameId: string | null
  name: string | null
}

export type CustomScoreTemplateCountAggregateOutputType = {
  id: number
  gameId: number
  name: number
  fields: number
  _all: number
}


export type CustomScoreTemplateMinAggregateInputType = {
  id?: true
  gameId?: true
  name?: true
}

export type CustomScoreTemplateMaxAggregateInputType = {
  id?: true
  gameId?: true
  name?: true
}

export type CustomScoreTemplateCountAggregateInputType = {
  id?: true
  gameId?: true
  name?: true
  fields?: true
  _all?: true
}

export type CustomScoreTemplateAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CustomScoreTemplate to aggregate.
   */
  where?: Prisma.CustomScoreTemplateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CustomScoreTemplates to fetch.
   */
  orderBy?: Prisma.CustomScoreTemplateOrderByWithRelationInput | Prisma.CustomScoreTemplateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CustomScoreTemplateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CustomScoreTemplates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CustomScoreTemplates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CustomScoreTemplates
  **/
  _count?: true | CustomScoreTemplateCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CustomScoreTemplateMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CustomScoreTemplateMaxAggregateInputType
}

export type GetCustomScoreTemplateAggregateType<T extends CustomScoreTemplateAggregateArgs> = {
      [P in keyof T & keyof AggregateCustomScoreTemplate]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCustomScoreTemplate[P]>
    : Prisma.GetScalarType<T[P], AggregateCustomScoreTemplate[P]>
}




export type CustomScoreTemplateGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CustomScoreTemplateWhereInput
  orderBy?: Prisma.CustomScoreTemplateOrderByWithAggregationInput | Prisma.CustomScoreTemplateOrderByWithAggregationInput[]
  by: Prisma.CustomScoreTemplateScalarFieldEnum[] | Prisma.CustomScoreTemplateScalarFieldEnum
  having?: Prisma.CustomScoreTemplateScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CustomScoreTemplateCountAggregateInputType | true
  _min?: CustomScoreTemplateMinAggregateInputType
  _max?: CustomScoreTemplateMaxAggregateInputType
}

export type CustomScoreTemplateGroupByOutputType = {
  id: string
  gameId: string
  name: string
  fields: runtime.JsonValue
  _count: CustomScoreTemplateCountAggregateOutputType | null
  _min: CustomScoreTemplateMinAggregateOutputType | null
  _max: CustomScoreTemplateMaxAggregateOutputType | null
}

type GetCustomScoreTemplateGroupByPayload<T extends CustomScoreTemplateGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CustomScoreTemplateGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CustomScoreTemplateGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CustomScoreTemplateGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CustomScoreTemplateGroupByOutputType[P]>
      }
    >
  >



export type CustomScoreTemplateWhereInput = {
  AND?: Prisma.CustomScoreTemplateWhereInput | Prisma.CustomScoreTemplateWhereInput[]
  OR?: Prisma.CustomScoreTemplateWhereInput[]
  NOT?: Prisma.CustomScoreTemplateWhereInput | Prisma.CustomScoreTemplateWhereInput[]
  id?: Prisma.StringFilter<"CustomScoreTemplate"> | string
  gameId?: Prisma.StringFilter<"CustomScoreTemplate"> | string
  name?: Prisma.StringFilter<"CustomScoreTemplate"> | string
  fields?: Prisma.JsonFilter<"CustomScoreTemplate">
  game?: Prisma.XOR<Prisma.GameScalarRelationFilter, Prisma.GameWhereInput>
  sessions?: Prisma.SessionListRelationFilter
}

export type CustomScoreTemplateOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  fields?: Prisma.SortOrder
  game?: Prisma.GameOrderByWithRelationInput
  sessions?: Prisma.SessionOrderByRelationAggregateInput
}

export type CustomScoreTemplateWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CustomScoreTemplateWhereInput | Prisma.CustomScoreTemplateWhereInput[]
  OR?: Prisma.CustomScoreTemplateWhereInput[]
  NOT?: Prisma.CustomScoreTemplateWhereInput | Prisma.CustomScoreTemplateWhereInput[]
  gameId?: Prisma.StringFilter<"CustomScoreTemplate"> | string
  name?: Prisma.StringFilter<"CustomScoreTemplate"> | string
  fields?: Prisma.JsonFilter<"CustomScoreTemplate">
  game?: Prisma.XOR<Prisma.GameScalarRelationFilter, Prisma.GameWhereInput>
  sessions?: Prisma.SessionListRelationFilter
}, "id">

export type CustomScoreTemplateOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  fields?: Prisma.SortOrder
  _count?: Prisma.CustomScoreTemplateCountOrderByAggregateInput
  _max?: Prisma.CustomScoreTemplateMaxOrderByAggregateInput
  _min?: Prisma.CustomScoreTemplateMinOrderByAggregateInput
}

export type CustomScoreTemplateScalarWhereWithAggregatesInput = {
  AND?: Prisma.CustomScoreTemplateScalarWhereWithAggregatesInput | Prisma.CustomScoreTemplateScalarWhereWithAggregatesInput[]
  OR?: Prisma.CustomScoreTemplateScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CustomScoreTemplateScalarWhereWithAggregatesInput | Prisma.CustomScoreTemplateScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CustomScoreTemplate"> | string
  gameId?: Prisma.StringWithAggregatesFilter<"CustomScoreTemplate"> | string
  name?: Prisma.StringWithAggregatesFilter<"CustomScoreTemplate"> | string
  fields?: Prisma.JsonWithAggregatesFilter<"CustomScoreTemplate">
}

export type CustomScoreTemplateCreateInput = {
  id?: string
  name: string
  fields: Prisma.JsonNullValueInput | runtime.InputJsonValue
  game: Prisma.GameCreateNestedOneWithoutTemplatesInput
  sessions?: Prisma.SessionCreateNestedManyWithoutTemplateInput
}

export type CustomScoreTemplateUncheckedCreateInput = {
  id?: string
  gameId: string
  name: string
  fields: Prisma.JsonNullValueInput | runtime.InputJsonValue
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutTemplateInput
}

export type CustomScoreTemplateUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  fields?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  game?: Prisma.GameUpdateOneRequiredWithoutTemplatesNestedInput
  sessions?: Prisma.SessionUpdateManyWithoutTemplateNestedInput
}

export type CustomScoreTemplateUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gameId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  fields?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutTemplateNestedInput
}

export type CustomScoreTemplateCreateManyInput = {
  id?: string
  gameId: string
  name: string
  fields: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type CustomScoreTemplateUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  fields?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type CustomScoreTemplateUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gameId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  fields?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type CustomScoreTemplateListRelationFilter = {
  every?: Prisma.CustomScoreTemplateWhereInput
  some?: Prisma.CustomScoreTemplateWhereInput
  none?: Prisma.CustomScoreTemplateWhereInput
}

export type CustomScoreTemplateOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CustomScoreTemplateCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  fields?: Prisma.SortOrder
}

export type CustomScoreTemplateMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type CustomScoreTemplateMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type CustomScoreTemplateNullableScalarRelationFilter = {
  is?: Prisma.CustomScoreTemplateWhereInput | null
  isNot?: Prisma.CustomScoreTemplateWhereInput | null
}

export type CustomScoreTemplateCreateNestedManyWithoutGameInput = {
  create?: Prisma.XOR<Prisma.CustomScoreTemplateCreateWithoutGameInput, Prisma.CustomScoreTemplateUncheckedCreateWithoutGameInput> | Prisma.CustomScoreTemplateCreateWithoutGameInput[] | Prisma.CustomScoreTemplateUncheckedCreateWithoutGameInput[]
  connectOrCreate?: Prisma.CustomScoreTemplateCreateOrConnectWithoutGameInput | Prisma.CustomScoreTemplateCreateOrConnectWithoutGameInput[]
  createMany?: Prisma.CustomScoreTemplateCreateManyGameInputEnvelope
  connect?: Prisma.CustomScoreTemplateWhereUniqueInput | Prisma.CustomScoreTemplateWhereUniqueInput[]
}

export type CustomScoreTemplateUncheckedCreateNestedManyWithoutGameInput = {
  create?: Prisma.XOR<Prisma.CustomScoreTemplateCreateWithoutGameInput, Prisma.CustomScoreTemplateUncheckedCreateWithoutGameInput> | Prisma.CustomScoreTemplateCreateWithoutGameInput[] | Prisma.CustomScoreTemplateUncheckedCreateWithoutGameInput[]
  connectOrCreate?: Prisma.CustomScoreTemplateCreateOrConnectWithoutGameInput | Prisma.CustomScoreTemplateCreateOrConnectWithoutGameInput[]
  createMany?: Prisma.CustomScoreTemplateCreateManyGameInputEnvelope
  connect?: Prisma.CustomScoreTemplateWhereUniqueInput | Prisma.CustomScoreTemplateWhereUniqueInput[]
}

export type CustomScoreTemplateUpdateManyWithoutGameNestedInput = {
  create?: Prisma.XOR<Prisma.CustomScoreTemplateCreateWithoutGameInput, Prisma.CustomScoreTemplateUncheckedCreateWithoutGameInput> | Prisma.CustomScoreTemplateCreateWithoutGameInput[] | Prisma.CustomScoreTemplateUncheckedCreateWithoutGameInput[]
  connectOrCreate?: Prisma.CustomScoreTemplateCreateOrConnectWithoutGameInput | Prisma.CustomScoreTemplateCreateOrConnectWithoutGameInput[]
  upsert?: Prisma.CustomScoreTemplateUpsertWithWhereUniqueWithoutGameInput | Prisma.CustomScoreTemplateUpsertWithWhereUniqueWithoutGameInput[]
  createMany?: Prisma.CustomScoreTemplateCreateManyGameInputEnvelope
  set?: Prisma.CustomScoreTemplateWhereUniqueInput | Prisma.CustomScoreTemplateWhereUniqueInput[]
  disconnect?: Prisma.CustomScoreTemplateWhereUniqueInput | Prisma.CustomScoreTemplateWhereUniqueInput[]
  delete?: Prisma.CustomScoreTemplateWhereUniqueInput | Prisma.CustomScoreTemplateWhereUniqueInput[]
  connect?: Prisma.CustomScoreTemplateWhereUniqueInput | Prisma.CustomScoreTemplateWhereUniqueInput[]
  update?: Prisma.CustomScoreTemplateUpdateWithWhereUniqueWithoutGameInput | Prisma.CustomScoreTemplateUpdateWithWhereUniqueWithoutGameInput[]
  updateMany?: Prisma.CustomScoreTemplateUpdateManyWithWhereWithoutGameInput | Prisma.CustomScoreTemplateUpdateManyWithWhereWithoutGameInput[]
  deleteMany?: Prisma.CustomScoreTemplateScalarWhereInput | Prisma.CustomScoreTemplateScalarWhereInput[]
}

export type CustomScoreTemplateUncheckedUpdateManyWithoutGameNestedInput = {
  create?: Prisma.XOR<Prisma.CustomScoreTemplateCreateWithoutGameInput, Prisma.CustomScoreTemplateUncheckedCreateWithoutGameInput> | Prisma.CustomScoreTemplateCreateWithoutGameInput[] | Prisma.CustomScoreTemplateUncheckedCreateWithoutGameInput[]
  connectOrCreate?: Prisma.CustomScoreTemplateCreateOrConnectWithoutGameInput | Prisma.CustomScoreTemplateCreateOrConnectWithoutGameInput[]
  upsert?: Prisma.CustomScoreTemplateUpsertWithWhereUniqueWithoutGameInput | Prisma.CustomScoreTemplateUpsertWithWhereUniqueWithoutGameInput[]
  createMany?: Prisma.CustomScoreTemplateCreateManyGameInputEnvelope
  set?: Prisma.CustomScoreTemplateWhereUniqueInput | Prisma.CustomScoreTemplateWhereUniqueInput[]
  disconnect?: Prisma.CustomScoreTemplateWhereUniqueInput | Prisma.CustomScoreTemplateWhereUniqueInput[]
  delete?: Prisma.CustomScoreTemplateWhereUniqueInput | Prisma.CustomScoreTemplateWhereUniqueInput[]
  connect?: Prisma.CustomScoreTemplateWhereUniqueInput | Prisma.CustomScoreTemplateWhereUniqueInput[]
  update?: Prisma.CustomScoreTemplateUpdateWithWhereUniqueWithoutGameInput | Prisma.CustomScoreTemplateUpdateWithWhereUniqueWithoutGameInput[]
  updateMany?: Prisma.CustomScoreTemplateUpdateManyWithWhereWithoutGameInput | Prisma.CustomScoreTemplateUpdateManyWithWhereWithoutGameInput[]
  deleteMany?: Prisma.CustomScoreTemplateScalarWhereInput | Prisma.CustomScoreTemplateScalarWhereInput[]
}

export type CustomScoreTemplateCreateNestedOneWithoutSessionsInput = {
  create?: Prisma.XOR<Prisma.CustomScoreTemplateCreateWithoutSessionsInput, Prisma.CustomScoreTemplateUncheckedCreateWithoutSessionsInput>
  connectOrCreate?: Prisma.CustomScoreTemplateCreateOrConnectWithoutSessionsInput
  connect?: Prisma.CustomScoreTemplateWhereUniqueInput
}

export type CustomScoreTemplateUpdateOneWithoutSessionsNestedInput = {
  create?: Prisma.XOR<Prisma.CustomScoreTemplateCreateWithoutSessionsInput, Prisma.CustomScoreTemplateUncheckedCreateWithoutSessionsInput>
  connectOrCreate?: Prisma.CustomScoreTemplateCreateOrConnectWithoutSessionsInput
  upsert?: Prisma.CustomScoreTemplateUpsertWithoutSessionsInput
  disconnect?: Prisma.CustomScoreTemplateWhereInput | boolean
  delete?: Prisma.CustomScoreTemplateWhereInput | boolean
  connect?: Prisma.CustomScoreTemplateWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CustomScoreTemplateUpdateToOneWithWhereWithoutSessionsInput, Prisma.CustomScoreTemplateUpdateWithoutSessionsInput>, Prisma.CustomScoreTemplateUncheckedUpdateWithoutSessionsInput>
}

export type CustomScoreTemplateCreateWithoutGameInput = {
  id?: string
  name: string
  fields: Prisma.JsonNullValueInput | runtime.InputJsonValue
  sessions?: Prisma.SessionCreateNestedManyWithoutTemplateInput
}

export type CustomScoreTemplateUncheckedCreateWithoutGameInput = {
  id?: string
  name: string
  fields: Prisma.JsonNullValueInput | runtime.InputJsonValue
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutTemplateInput
}

export type CustomScoreTemplateCreateOrConnectWithoutGameInput = {
  where: Prisma.CustomScoreTemplateWhereUniqueInput
  create: Prisma.XOR<Prisma.CustomScoreTemplateCreateWithoutGameInput, Prisma.CustomScoreTemplateUncheckedCreateWithoutGameInput>
}

export type CustomScoreTemplateCreateManyGameInputEnvelope = {
  data: Prisma.CustomScoreTemplateCreateManyGameInput | Prisma.CustomScoreTemplateCreateManyGameInput[]
}

export type CustomScoreTemplateUpsertWithWhereUniqueWithoutGameInput = {
  where: Prisma.CustomScoreTemplateWhereUniqueInput
  update: Prisma.XOR<Prisma.CustomScoreTemplateUpdateWithoutGameInput, Prisma.CustomScoreTemplateUncheckedUpdateWithoutGameInput>
  create: Prisma.XOR<Prisma.CustomScoreTemplateCreateWithoutGameInput, Prisma.CustomScoreTemplateUncheckedCreateWithoutGameInput>
}

export type CustomScoreTemplateUpdateWithWhereUniqueWithoutGameInput = {
  where: Prisma.CustomScoreTemplateWhereUniqueInput
  data: Prisma.XOR<Prisma.CustomScoreTemplateUpdateWithoutGameInput, Prisma.CustomScoreTemplateUncheckedUpdateWithoutGameInput>
}

export type CustomScoreTemplateUpdateManyWithWhereWithoutGameInput = {
  where: Prisma.CustomScoreTemplateScalarWhereInput
  data: Prisma.XOR<Prisma.CustomScoreTemplateUpdateManyMutationInput, Prisma.CustomScoreTemplateUncheckedUpdateManyWithoutGameInput>
}

export type CustomScoreTemplateScalarWhereInput = {
  AND?: Prisma.CustomScoreTemplateScalarWhereInput | Prisma.CustomScoreTemplateScalarWhereInput[]
  OR?: Prisma.CustomScoreTemplateScalarWhereInput[]
  NOT?: Prisma.CustomScoreTemplateScalarWhereInput | Prisma.CustomScoreTemplateScalarWhereInput[]
  id?: Prisma.StringFilter<"CustomScoreTemplate"> | string
  gameId?: Prisma.StringFilter<"CustomScoreTemplate"> | string
  name?: Prisma.StringFilter<"CustomScoreTemplate"> | string
  fields?: Prisma.JsonFilter<"CustomScoreTemplate">
}

export type CustomScoreTemplateCreateWithoutSessionsInput = {
  id?: string
  name: string
  fields: Prisma.JsonNullValueInput | runtime.InputJsonValue
  game: Prisma.GameCreateNestedOneWithoutTemplatesInput
}

export type CustomScoreTemplateUncheckedCreateWithoutSessionsInput = {
  id?: string
  gameId: string
  name: string
  fields: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type CustomScoreTemplateCreateOrConnectWithoutSessionsInput = {
  where: Prisma.CustomScoreTemplateWhereUniqueInput
  create: Prisma.XOR<Prisma.CustomScoreTemplateCreateWithoutSessionsInput, Prisma.CustomScoreTemplateUncheckedCreateWithoutSessionsInput>
}

export type CustomScoreTemplateUpsertWithoutSessionsInput = {
  update: Prisma.XOR<Prisma.CustomScoreTemplateUpdateWithoutSessionsInput, Prisma.CustomScoreTemplateUncheckedUpdateWithoutSessionsInput>
  create: Prisma.XOR<Prisma.CustomScoreTemplateCreateWithoutSessionsInput, Prisma.CustomScoreTemplateUncheckedCreateWithoutSessionsInput>
  where?: Prisma.CustomScoreTemplateWhereInput
}

export type CustomScoreTemplateUpdateToOneWithWhereWithoutSessionsInput = {
  where?: Prisma.CustomScoreTemplateWhereInput
  data: Prisma.XOR<Prisma.CustomScoreTemplateUpdateWithoutSessionsInput, Prisma.CustomScoreTemplateUncheckedUpdateWithoutSessionsInput>
}

export type CustomScoreTemplateUpdateWithoutSessionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  fields?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  game?: Prisma.GameUpdateOneRequiredWithoutTemplatesNestedInput
}

export type CustomScoreTemplateUncheckedUpdateWithoutSessionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gameId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  fields?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type CustomScoreTemplateCreateManyGameInput = {
  id?: string
  name: string
  fields: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type CustomScoreTemplateUpdateWithoutGameInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  fields?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  sessions?: Prisma.SessionUpdateManyWithoutTemplateNestedInput
}

export type CustomScoreTemplateUncheckedUpdateWithoutGameInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  fields?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutTemplateNestedInput
}

export type CustomScoreTemplateUncheckedUpdateManyWithoutGameInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  fields?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}


/**
 * Count Type CustomScoreTemplateCountOutputType
 */

export type CustomScoreTemplateCountOutputType = {
  sessions: number
}

export type CustomScoreTemplateCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sessions?: boolean | CustomScoreTemplateCountOutputTypeCountSessionsArgs
}

/**
 * CustomScoreTemplateCountOutputType without action
 */
export type CustomScoreTemplateCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomScoreTemplateCountOutputType
   */
  select?: Prisma.CustomScoreTemplateCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CustomScoreTemplateCountOutputType without action
 */
export type CustomScoreTemplateCountOutputTypeCountSessionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SessionWhereInput
}


export type CustomScoreTemplateSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  gameId?: boolean
  name?: boolean
  fields?: boolean
  game?: boolean | Prisma.GameDefaultArgs<ExtArgs>
  sessions?: boolean | Prisma.CustomScoreTemplate$sessionsArgs<ExtArgs>
  _count?: boolean | Prisma.CustomScoreTemplateCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["customScoreTemplate"]>

export type CustomScoreTemplateSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  gameId?: boolean
  name?: boolean
  fields?: boolean
  game?: boolean | Prisma.GameDefaultArgs<ExtArgs>
}, ExtArgs["result"]["customScoreTemplate"]>

export type CustomScoreTemplateSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  gameId?: boolean
  name?: boolean
  fields?: boolean
  game?: boolean | Prisma.GameDefaultArgs<ExtArgs>
}, ExtArgs["result"]["customScoreTemplate"]>

export type CustomScoreTemplateSelectScalar = {
  id?: boolean
  gameId?: boolean
  name?: boolean
  fields?: boolean
}

export type CustomScoreTemplateOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "gameId" | "name" | "fields", ExtArgs["result"]["customScoreTemplate"]>
export type CustomScoreTemplateInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  game?: boolean | Prisma.GameDefaultArgs<ExtArgs>
  sessions?: boolean | Prisma.CustomScoreTemplate$sessionsArgs<ExtArgs>
  _count?: boolean | Prisma.CustomScoreTemplateCountOutputTypeDefaultArgs<ExtArgs>
}
export type CustomScoreTemplateIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  game?: boolean | Prisma.GameDefaultArgs<ExtArgs>
}
export type CustomScoreTemplateIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  game?: boolean | Prisma.GameDefaultArgs<ExtArgs>
}

export type $CustomScoreTemplatePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CustomScoreTemplate"
  objects: {
    game: Prisma.$GamePayload<ExtArgs>
    sessions: Prisma.$SessionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    gameId: string
    name: string
    fields: runtime.JsonValue
  }, ExtArgs["result"]["customScoreTemplate"]>
  composites: {}
}

export type CustomScoreTemplateGetPayload<S extends boolean | null | undefined | CustomScoreTemplateDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CustomScoreTemplatePayload, S>

export type CustomScoreTemplateCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CustomScoreTemplateFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CustomScoreTemplateCountAggregateInputType | true
  }

export interface CustomScoreTemplateDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CustomScoreTemplate'], meta: { name: 'CustomScoreTemplate' } }
  /**
   * Find zero or one CustomScoreTemplate that matches the filter.
   * @param {CustomScoreTemplateFindUniqueArgs} args - Arguments to find a CustomScoreTemplate
   * @example
   * // Get one CustomScoreTemplate
   * const customScoreTemplate = await prisma.customScoreTemplate.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CustomScoreTemplateFindUniqueArgs>(args: Prisma.SelectSubset<T, CustomScoreTemplateFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CustomScoreTemplateClient<runtime.Types.Result.GetResult<Prisma.$CustomScoreTemplatePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CustomScoreTemplate that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CustomScoreTemplateFindUniqueOrThrowArgs} args - Arguments to find a CustomScoreTemplate
   * @example
   * // Get one CustomScoreTemplate
   * const customScoreTemplate = await prisma.customScoreTemplate.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CustomScoreTemplateFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CustomScoreTemplateFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CustomScoreTemplateClient<runtime.Types.Result.GetResult<Prisma.$CustomScoreTemplatePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CustomScoreTemplate that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomScoreTemplateFindFirstArgs} args - Arguments to find a CustomScoreTemplate
   * @example
   * // Get one CustomScoreTemplate
   * const customScoreTemplate = await prisma.customScoreTemplate.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CustomScoreTemplateFindFirstArgs>(args?: Prisma.SelectSubset<T, CustomScoreTemplateFindFirstArgs<ExtArgs>>): Prisma.Prisma__CustomScoreTemplateClient<runtime.Types.Result.GetResult<Prisma.$CustomScoreTemplatePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CustomScoreTemplate that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomScoreTemplateFindFirstOrThrowArgs} args - Arguments to find a CustomScoreTemplate
   * @example
   * // Get one CustomScoreTemplate
   * const customScoreTemplate = await prisma.customScoreTemplate.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CustomScoreTemplateFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CustomScoreTemplateFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CustomScoreTemplateClient<runtime.Types.Result.GetResult<Prisma.$CustomScoreTemplatePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CustomScoreTemplates that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomScoreTemplateFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CustomScoreTemplates
   * const customScoreTemplates = await prisma.customScoreTemplate.findMany()
   * 
   * // Get first 10 CustomScoreTemplates
   * const customScoreTemplates = await prisma.customScoreTemplate.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const customScoreTemplateWithIdOnly = await prisma.customScoreTemplate.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CustomScoreTemplateFindManyArgs>(args?: Prisma.SelectSubset<T, CustomScoreTemplateFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CustomScoreTemplatePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CustomScoreTemplate.
   * @param {CustomScoreTemplateCreateArgs} args - Arguments to create a CustomScoreTemplate.
   * @example
   * // Create one CustomScoreTemplate
   * const CustomScoreTemplate = await prisma.customScoreTemplate.create({
   *   data: {
   *     // ... data to create a CustomScoreTemplate
   *   }
   * })
   * 
   */
  create<T extends CustomScoreTemplateCreateArgs>(args: Prisma.SelectSubset<T, CustomScoreTemplateCreateArgs<ExtArgs>>): Prisma.Prisma__CustomScoreTemplateClient<runtime.Types.Result.GetResult<Prisma.$CustomScoreTemplatePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CustomScoreTemplates.
   * @param {CustomScoreTemplateCreateManyArgs} args - Arguments to create many CustomScoreTemplates.
   * @example
   * // Create many CustomScoreTemplates
   * const customScoreTemplate = await prisma.customScoreTemplate.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CustomScoreTemplateCreateManyArgs>(args?: Prisma.SelectSubset<T, CustomScoreTemplateCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CustomScoreTemplates and returns the data saved in the database.
   * @param {CustomScoreTemplateCreateManyAndReturnArgs} args - Arguments to create many CustomScoreTemplates.
   * @example
   * // Create many CustomScoreTemplates
   * const customScoreTemplate = await prisma.customScoreTemplate.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CustomScoreTemplates and only return the `id`
   * const customScoreTemplateWithIdOnly = await prisma.customScoreTemplate.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CustomScoreTemplateCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CustomScoreTemplateCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CustomScoreTemplatePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CustomScoreTemplate.
   * @param {CustomScoreTemplateDeleteArgs} args - Arguments to delete one CustomScoreTemplate.
   * @example
   * // Delete one CustomScoreTemplate
   * const CustomScoreTemplate = await prisma.customScoreTemplate.delete({
   *   where: {
   *     // ... filter to delete one CustomScoreTemplate
   *   }
   * })
   * 
   */
  delete<T extends CustomScoreTemplateDeleteArgs>(args: Prisma.SelectSubset<T, CustomScoreTemplateDeleteArgs<ExtArgs>>): Prisma.Prisma__CustomScoreTemplateClient<runtime.Types.Result.GetResult<Prisma.$CustomScoreTemplatePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CustomScoreTemplate.
   * @param {CustomScoreTemplateUpdateArgs} args - Arguments to update one CustomScoreTemplate.
   * @example
   * // Update one CustomScoreTemplate
   * const customScoreTemplate = await prisma.customScoreTemplate.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CustomScoreTemplateUpdateArgs>(args: Prisma.SelectSubset<T, CustomScoreTemplateUpdateArgs<ExtArgs>>): Prisma.Prisma__CustomScoreTemplateClient<runtime.Types.Result.GetResult<Prisma.$CustomScoreTemplatePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CustomScoreTemplates.
   * @param {CustomScoreTemplateDeleteManyArgs} args - Arguments to filter CustomScoreTemplates to delete.
   * @example
   * // Delete a few CustomScoreTemplates
   * const { count } = await prisma.customScoreTemplate.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CustomScoreTemplateDeleteManyArgs>(args?: Prisma.SelectSubset<T, CustomScoreTemplateDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CustomScoreTemplates.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomScoreTemplateUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CustomScoreTemplates
   * const customScoreTemplate = await prisma.customScoreTemplate.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CustomScoreTemplateUpdateManyArgs>(args: Prisma.SelectSubset<T, CustomScoreTemplateUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CustomScoreTemplates and returns the data updated in the database.
   * @param {CustomScoreTemplateUpdateManyAndReturnArgs} args - Arguments to update many CustomScoreTemplates.
   * @example
   * // Update many CustomScoreTemplates
   * const customScoreTemplate = await prisma.customScoreTemplate.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CustomScoreTemplates and only return the `id`
   * const customScoreTemplateWithIdOnly = await prisma.customScoreTemplate.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CustomScoreTemplateUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CustomScoreTemplateUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CustomScoreTemplatePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CustomScoreTemplate.
   * @param {CustomScoreTemplateUpsertArgs} args - Arguments to update or create a CustomScoreTemplate.
   * @example
   * // Update or create a CustomScoreTemplate
   * const customScoreTemplate = await prisma.customScoreTemplate.upsert({
   *   create: {
   *     // ... data to create a CustomScoreTemplate
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CustomScoreTemplate we want to update
   *   }
   * })
   */
  upsert<T extends CustomScoreTemplateUpsertArgs>(args: Prisma.SelectSubset<T, CustomScoreTemplateUpsertArgs<ExtArgs>>): Prisma.Prisma__CustomScoreTemplateClient<runtime.Types.Result.GetResult<Prisma.$CustomScoreTemplatePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CustomScoreTemplates.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomScoreTemplateCountArgs} args - Arguments to filter CustomScoreTemplates to count.
   * @example
   * // Count the number of CustomScoreTemplates
   * const count = await prisma.customScoreTemplate.count({
   *   where: {
   *     // ... the filter for the CustomScoreTemplates we want to count
   *   }
   * })
  **/
  count<T extends CustomScoreTemplateCountArgs>(
    args?: Prisma.Subset<T, CustomScoreTemplateCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CustomScoreTemplateCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CustomScoreTemplate.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomScoreTemplateAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CustomScoreTemplateAggregateArgs>(args: Prisma.Subset<T, CustomScoreTemplateAggregateArgs>): Prisma.PrismaPromise<GetCustomScoreTemplateAggregateType<T>>

  /**
   * Group by CustomScoreTemplate.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomScoreTemplateGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CustomScoreTemplateGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CustomScoreTemplateGroupByArgs['orderBy'] }
      : { orderBy?: CustomScoreTemplateGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CustomScoreTemplateGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCustomScoreTemplateGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CustomScoreTemplate model
 */
readonly fields: CustomScoreTemplateFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CustomScoreTemplate.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CustomScoreTemplateClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  game<T extends Prisma.GameDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GameDefaultArgs<ExtArgs>>): Prisma.Prisma__GameClient<runtime.Types.Result.GetResult<Prisma.$GamePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  sessions<T extends Prisma.CustomScoreTemplate$sessionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CustomScoreTemplate$sessionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CustomScoreTemplate model
 */
export interface CustomScoreTemplateFieldRefs {
  readonly id: Prisma.FieldRef<"CustomScoreTemplate", 'String'>
  readonly gameId: Prisma.FieldRef<"CustomScoreTemplate", 'String'>
  readonly name: Prisma.FieldRef<"CustomScoreTemplate", 'String'>
  readonly fields: Prisma.FieldRef<"CustomScoreTemplate", 'Json'>
}
    

// Custom InputTypes
/**
 * CustomScoreTemplate findUnique
 */
export type CustomScoreTemplateFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomScoreTemplate
   */
  select?: Prisma.CustomScoreTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomScoreTemplate
   */
  omit?: Prisma.CustomScoreTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomScoreTemplateInclude<ExtArgs> | null
  /**
   * Filter, which CustomScoreTemplate to fetch.
   */
  where: Prisma.CustomScoreTemplateWhereUniqueInput
}

/**
 * CustomScoreTemplate findUniqueOrThrow
 */
export type CustomScoreTemplateFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomScoreTemplate
   */
  select?: Prisma.CustomScoreTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomScoreTemplate
   */
  omit?: Prisma.CustomScoreTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomScoreTemplateInclude<ExtArgs> | null
  /**
   * Filter, which CustomScoreTemplate to fetch.
   */
  where: Prisma.CustomScoreTemplateWhereUniqueInput
}

/**
 * CustomScoreTemplate findFirst
 */
export type CustomScoreTemplateFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomScoreTemplate
   */
  select?: Prisma.CustomScoreTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomScoreTemplate
   */
  omit?: Prisma.CustomScoreTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomScoreTemplateInclude<ExtArgs> | null
  /**
   * Filter, which CustomScoreTemplate to fetch.
   */
  where?: Prisma.CustomScoreTemplateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CustomScoreTemplates to fetch.
   */
  orderBy?: Prisma.CustomScoreTemplateOrderByWithRelationInput | Prisma.CustomScoreTemplateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CustomScoreTemplates.
   */
  cursor?: Prisma.CustomScoreTemplateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CustomScoreTemplates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CustomScoreTemplates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CustomScoreTemplates.
   */
  distinct?: Prisma.CustomScoreTemplateScalarFieldEnum | Prisma.CustomScoreTemplateScalarFieldEnum[]
}

/**
 * CustomScoreTemplate findFirstOrThrow
 */
export type CustomScoreTemplateFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomScoreTemplate
   */
  select?: Prisma.CustomScoreTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomScoreTemplate
   */
  omit?: Prisma.CustomScoreTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomScoreTemplateInclude<ExtArgs> | null
  /**
   * Filter, which CustomScoreTemplate to fetch.
   */
  where?: Prisma.CustomScoreTemplateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CustomScoreTemplates to fetch.
   */
  orderBy?: Prisma.CustomScoreTemplateOrderByWithRelationInput | Prisma.CustomScoreTemplateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CustomScoreTemplates.
   */
  cursor?: Prisma.CustomScoreTemplateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CustomScoreTemplates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CustomScoreTemplates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CustomScoreTemplates.
   */
  distinct?: Prisma.CustomScoreTemplateScalarFieldEnum | Prisma.CustomScoreTemplateScalarFieldEnum[]
}

/**
 * CustomScoreTemplate findMany
 */
export type CustomScoreTemplateFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomScoreTemplate
   */
  select?: Prisma.CustomScoreTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomScoreTemplate
   */
  omit?: Prisma.CustomScoreTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomScoreTemplateInclude<ExtArgs> | null
  /**
   * Filter, which CustomScoreTemplates to fetch.
   */
  where?: Prisma.CustomScoreTemplateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CustomScoreTemplates to fetch.
   */
  orderBy?: Prisma.CustomScoreTemplateOrderByWithRelationInput | Prisma.CustomScoreTemplateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CustomScoreTemplates.
   */
  cursor?: Prisma.CustomScoreTemplateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CustomScoreTemplates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CustomScoreTemplates.
   */
  skip?: number
  distinct?: Prisma.CustomScoreTemplateScalarFieldEnum | Prisma.CustomScoreTemplateScalarFieldEnum[]
}

/**
 * CustomScoreTemplate create
 */
export type CustomScoreTemplateCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomScoreTemplate
   */
  select?: Prisma.CustomScoreTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomScoreTemplate
   */
  omit?: Prisma.CustomScoreTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomScoreTemplateInclude<ExtArgs> | null
  /**
   * The data needed to create a CustomScoreTemplate.
   */
  data: Prisma.XOR<Prisma.CustomScoreTemplateCreateInput, Prisma.CustomScoreTemplateUncheckedCreateInput>
}

/**
 * CustomScoreTemplate createMany
 */
export type CustomScoreTemplateCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CustomScoreTemplates.
   */
  data: Prisma.CustomScoreTemplateCreateManyInput | Prisma.CustomScoreTemplateCreateManyInput[]
}

/**
 * CustomScoreTemplate createManyAndReturn
 */
export type CustomScoreTemplateCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomScoreTemplate
   */
  select?: Prisma.CustomScoreTemplateSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CustomScoreTemplate
   */
  omit?: Prisma.CustomScoreTemplateOmit<ExtArgs> | null
  /**
   * The data used to create many CustomScoreTemplates.
   */
  data: Prisma.CustomScoreTemplateCreateManyInput | Prisma.CustomScoreTemplateCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomScoreTemplateIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CustomScoreTemplate update
 */
export type CustomScoreTemplateUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomScoreTemplate
   */
  select?: Prisma.CustomScoreTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomScoreTemplate
   */
  omit?: Prisma.CustomScoreTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomScoreTemplateInclude<ExtArgs> | null
  /**
   * The data needed to update a CustomScoreTemplate.
   */
  data: Prisma.XOR<Prisma.CustomScoreTemplateUpdateInput, Prisma.CustomScoreTemplateUncheckedUpdateInput>
  /**
   * Choose, which CustomScoreTemplate to update.
   */
  where: Prisma.CustomScoreTemplateWhereUniqueInput
}

/**
 * CustomScoreTemplate updateMany
 */
export type CustomScoreTemplateUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CustomScoreTemplates.
   */
  data: Prisma.XOR<Prisma.CustomScoreTemplateUpdateManyMutationInput, Prisma.CustomScoreTemplateUncheckedUpdateManyInput>
  /**
   * Filter which CustomScoreTemplates to update
   */
  where?: Prisma.CustomScoreTemplateWhereInput
  /**
   * Limit how many CustomScoreTemplates to update.
   */
  limit?: number
}

/**
 * CustomScoreTemplate updateManyAndReturn
 */
export type CustomScoreTemplateUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomScoreTemplate
   */
  select?: Prisma.CustomScoreTemplateSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CustomScoreTemplate
   */
  omit?: Prisma.CustomScoreTemplateOmit<ExtArgs> | null
  /**
   * The data used to update CustomScoreTemplates.
   */
  data: Prisma.XOR<Prisma.CustomScoreTemplateUpdateManyMutationInput, Prisma.CustomScoreTemplateUncheckedUpdateManyInput>
  /**
   * Filter which CustomScoreTemplates to update
   */
  where?: Prisma.CustomScoreTemplateWhereInput
  /**
   * Limit how many CustomScoreTemplates to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomScoreTemplateIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CustomScoreTemplate upsert
 */
export type CustomScoreTemplateUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomScoreTemplate
   */
  select?: Prisma.CustomScoreTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomScoreTemplate
   */
  omit?: Prisma.CustomScoreTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomScoreTemplateInclude<ExtArgs> | null
  /**
   * The filter to search for the CustomScoreTemplate to update in case it exists.
   */
  where: Prisma.CustomScoreTemplateWhereUniqueInput
  /**
   * In case the CustomScoreTemplate found by the `where` argument doesn't exist, create a new CustomScoreTemplate with this data.
   */
  create: Prisma.XOR<Prisma.CustomScoreTemplateCreateInput, Prisma.CustomScoreTemplateUncheckedCreateInput>
  /**
   * In case the CustomScoreTemplate was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CustomScoreTemplateUpdateInput, Prisma.CustomScoreTemplateUncheckedUpdateInput>
}

/**
 * CustomScoreTemplate delete
 */
export type CustomScoreTemplateDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomScoreTemplate
   */
  select?: Prisma.CustomScoreTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomScoreTemplate
   */
  omit?: Prisma.CustomScoreTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomScoreTemplateInclude<ExtArgs> | null
  /**
   * Filter which CustomScoreTemplate to delete.
   */
  where: Prisma.CustomScoreTemplateWhereUniqueInput
}

/**
 * CustomScoreTemplate deleteMany
 */
export type CustomScoreTemplateDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CustomScoreTemplates to delete
   */
  where?: Prisma.CustomScoreTemplateWhereInput
  /**
   * Limit how many CustomScoreTemplates to delete.
   */
  limit?: number
}

/**
 * CustomScoreTemplate.sessions
 */
export type CustomScoreTemplate$sessionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionInclude<ExtArgs> | null
  where?: Prisma.SessionWhereInput
  orderBy?: Prisma.SessionOrderByWithRelationInput | Prisma.SessionOrderByWithRelationInput[]
  cursor?: Prisma.SessionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SessionScalarFieldEnum | Prisma.SessionScalarFieldEnum[]
}

/**
 * CustomScoreTemplate without action
 */
export type CustomScoreTemplateDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomScoreTemplate
   */
  select?: Prisma.CustomScoreTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomScoreTemplate
   */
  omit?: Prisma.CustomScoreTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomScoreTemplateInclude<ExtArgs> | null
}
