
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SessionPlayer` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SessionPlayer
 * 
 */
export type SessionPlayerModel = runtime.Types.Result.DefaultSelection<Prisma.$SessionPlayerPayload>

export type AggregateSessionPlayer = {
  _count: SessionPlayerCountAggregateOutputType | null
  _avg: SessionPlayerAvgAggregateOutputType | null
  _sum: SessionPlayerSumAggregateOutputType | null
  _min: SessionPlayerMinAggregateOutputType | null
  _max: SessionPlayerMaxAggregateOutputType | null
}

export type SessionPlayerAvgAggregateOutputType = {
  rawScore: number | null
  placement: number | null
  pointsAwarded: number | null
}

export type SessionPlayerSumAggregateOutputType = {
  rawScore: number | null
  placement: number | null
  pointsAwarded: number | null
}

export type SessionPlayerMinAggregateOutputType = {
  id: string | null
  sessionId: string | null
  userId: string | null
  rawScore: number | null
  placement: number | null
  pointsAwarded: number | null
}

export type SessionPlayerMaxAggregateOutputType = {
  id: string | null
  sessionId: string | null
  userId: string | null
  rawScore: number | null
  placement: number | null
  pointsAwarded: number | null
}

export type SessionPlayerCountAggregateOutputType = {
  id: number
  sessionId: number
  userId: number
  rawScore: number
  placement: number
  pointsAwarded: number
  scoreDetails: number
  _all: number
}


export type SessionPlayerAvgAggregateInputType = {
  rawScore?: true
  placement?: true
  pointsAwarded?: true
}

export type SessionPlayerSumAggregateInputType = {
  rawScore?: true
  placement?: true
  pointsAwarded?: true
}

export type SessionPlayerMinAggregateInputType = {
  id?: true
  sessionId?: true
  userId?: true
  rawScore?: true
  placement?: true
  pointsAwarded?: true
}

export type SessionPlayerMaxAggregateInputType = {
  id?: true
  sessionId?: true
  userId?: true
  rawScore?: true
  placement?: true
  pointsAwarded?: true
}

export type SessionPlayerCountAggregateInputType = {
  id?: true
  sessionId?: true
  userId?: true
  rawScore?: true
  placement?: true
  pointsAwarded?: true
  scoreDetails?: true
  _all?: true
}

export type SessionPlayerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SessionPlayer to aggregate.
   */
  where?: Prisma.SessionPlayerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SessionPlayers to fetch.
   */
  orderBy?: Prisma.SessionPlayerOrderByWithRelationInput | Prisma.SessionPlayerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SessionPlayerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SessionPlayers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SessionPlayers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SessionPlayers
  **/
  _count?: true | SessionPlayerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SessionPlayerAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SessionPlayerSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SessionPlayerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SessionPlayerMaxAggregateInputType
}

export type GetSessionPlayerAggregateType<T extends SessionPlayerAggregateArgs> = {
      [P in keyof T & keyof AggregateSessionPlayer]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSessionPlayer[P]>
    : Prisma.GetScalarType<T[P], AggregateSessionPlayer[P]>
}




export type SessionPlayerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SessionPlayerWhereInput
  orderBy?: Prisma.SessionPlayerOrderByWithAggregationInput | Prisma.SessionPlayerOrderByWithAggregationInput[]
  by: Prisma.SessionPlayerScalarFieldEnum[] | Prisma.SessionPlayerScalarFieldEnum
  having?: Prisma.SessionPlayerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SessionPlayerCountAggregateInputType | true
  _avg?: SessionPlayerAvgAggregateInputType
  _sum?: SessionPlayerSumAggregateInputType
  _min?: SessionPlayerMinAggregateInputType
  _max?: SessionPlayerMaxAggregateInputType
}

export type SessionPlayerGroupByOutputType = {
  id: string
  sessionId: string
  userId: string
  rawScore: number
  placement: number
  pointsAwarded: number
  scoreDetails: runtime.JsonValue | null
  _count: SessionPlayerCountAggregateOutputType | null
  _avg: SessionPlayerAvgAggregateOutputType | null
  _sum: SessionPlayerSumAggregateOutputType | null
  _min: SessionPlayerMinAggregateOutputType | null
  _max: SessionPlayerMaxAggregateOutputType | null
}

type GetSessionPlayerGroupByPayload<T extends SessionPlayerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SessionPlayerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SessionPlayerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SessionPlayerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SessionPlayerGroupByOutputType[P]>
      }
    >
  >



export type SessionPlayerWhereInput = {
  AND?: Prisma.SessionPlayerWhereInput | Prisma.SessionPlayerWhereInput[]
  OR?: Prisma.SessionPlayerWhereInput[]
  NOT?: Prisma.SessionPlayerWhereInput | Prisma.SessionPlayerWhereInput[]
  id?: Prisma.StringFilter<"SessionPlayer"> | string
  sessionId?: Prisma.StringFilter<"SessionPlayer"> | string
  userId?: Prisma.StringFilter<"SessionPlayer"> | string
  rawScore?: Prisma.FloatFilter<"SessionPlayer"> | number
  placement?: Prisma.IntFilter<"SessionPlayer"> | number
  pointsAwarded?: Prisma.FloatFilter<"SessionPlayer"> | number
  scoreDetails?: Prisma.JsonNullableFilter<"SessionPlayer">
  session?: Prisma.XOR<Prisma.SessionScalarRelationFilter, Prisma.SessionWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type SessionPlayerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  rawScore?: Prisma.SortOrder
  placement?: Prisma.SortOrder
  pointsAwarded?: Prisma.SortOrder
  scoreDetails?: Prisma.SortOrderInput | Prisma.SortOrder
  session?: Prisma.SessionOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type SessionPlayerWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SessionPlayerWhereInput | Prisma.SessionPlayerWhereInput[]
  OR?: Prisma.SessionPlayerWhereInput[]
  NOT?: Prisma.SessionPlayerWhereInput | Prisma.SessionPlayerWhereInput[]
  sessionId?: Prisma.StringFilter<"SessionPlayer"> | string
  userId?: Prisma.StringFilter<"SessionPlayer"> | string
  rawScore?: Prisma.FloatFilter<"SessionPlayer"> | number
  placement?: Prisma.IntFilter<"SessionPlayer"> | number
  pointsAwarded?: Prisma.FloatFilter<"SessionPlayer"> | number
  scoreDetails?: Prisma.JsonNullableFilter<"SessionPlayer">
  session?: Prisma.XOR<Prisma.SessionScalarRelationFilter, Prisma.SessionWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type SessionPlayerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  rawScore?: Prisma.SortOrder
  placement?: Prisma.SortOrder
  pointsAwarded?: Prisma.SortOrder
  scoreDetails?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.SessionPlayerCountOrderByAggregateInput
  _avg?: Prisma.SessionPlayerAvgOrderByAggregateInput
  _max?: Prisma.SessionPlayerMaxOrderByAggregateInput
  _min?: Prisma.SessionPlayerMinOrderByAggregateInput
  _sum?: Prisma.SessionPlayerSumOrderByAggregateInput
}

export type SessionPlayerScalarWhereWithAggregatesInput = {
  AND?: Prisma.SessionPlayerScalarWhereWithAggregatesInput | Prisma.SessionPlayerScalarWhereWithAggregatesInput[]
  OR?: Prisma.SessionPlayerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SessionPlayerScalarWhereWithAggregatesInput | Prisma.SessionPlayerScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SessionPlayer"> | string
  sessionId?: Prisma.StringWithAggregatesFilter<"SessionPlayer"> | string
  userId?: Prisma.StringWithAggregatesFilter<"SessionPlayer"> | string
  rawScore?: Prisma.FloatWithAggregatesFilter<"SessionPlayer"> | number
  placement?: Prisma.IntWithAggregatesFilter<"SessionPlayer"> | number
  pointsAwarded?: Prisma.FloatWithAggregatesFilter<"SessionPlayer"> | number
  scoreDetails?: Prisma.JsonNullableWithAggregatesFilter<"SessionPlayer">
}

export type SessionPlayerCreateInput = {
  id?: string
  rawScore: number
  placement: number
  pointsAwarded: number
  scoreDetails?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  session: Prisma.SessionCreateNestedOneWithoutPlayersInput
  user: Prisma.UserCreateNestedOneWithoutSessionsInput
}

export type SessionPlayerUncheckedCreateInput = {
  id?: string
  sessionId: string
  userId: string
  rawScore: number
  placement: number
  pointsAwarded: number
  scoreDetails?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type SessionPlayerUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rawScore?: Prisma.FloatFieldUpdateOperationsInput | number
  placement?: Prisma.IntFieldUpdateOperationsInput | number
  pointsAwarded?: Prisma.FloatFieldUpdateOperationsInput | number
  scoreDetails?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  session?: Prisma.SessionUpdateOneRequiredWithoutPlayersNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutSessionsNestedInput
}

export type SessionPlayerUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  rawScore?: Prisma.FloatFieldUpdateOperationsInput | number
  placement?: Prisma.IntFieldUpdateOperationsInput | number
  pointsAwarded?: Prisma.FloatFieldUpdateOperationsInput | number
  scoreDetails?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type SessionPlayerCreateManyInput = {
  id?: string
  sessionId: string
  userId: string
  rawScore: number
  placement: number
  pointsAwarded: number
  scoreDetails?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type SessionPlayerUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rawScore?: Prisma.FloatFieldUpdateOperationsInput | number
  placement?: Prisma.IntFieldUpdateOperationsInput | number
  pointsAwarded?: Prisma.FloatFieldUpdateOperationsInput | number
  scoreDetails?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type SessionPlayerUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  rawScore?: Prisma.FloatFieldUpdateOperationsInput | number
  placement?: Prisma.IntFieldUpdateOperationsInput | number
  pointsAwarded?: Prisma.FloatFieldUpdateOperationsInput | number
  scoreDetails?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type SessionPlayerListRelationFilter = {
  every?: Prisma.SessionPlayerWhereInput
  some?: Prisma.SessionPlayerWhereInput
  none?: Prisma.SessionPlayerWhereInput
}

export type SessionPlayerOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SessionPlayerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  rawScore?: Prisma.SortOrder
  placement?: Prisma.SortOrder
  pointsAwarded?: Prisma.SortOrder
  scoreDetails?: Prisma.SortOrder
}

export type SessionPlayerAvgOrderByAggregateInput = {
  rawScore?: Prisma.SortOrder
  placement?: Prisma.SortOrder
  pointsAwarded?: Prisma.SortOrder
}

export type SessionPlayerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  rawScore?: Prisma.SortOrder
  placement?: Prisma.SortOrder
  pointsAwarded?: Prisma.SortOrder
}

export type SessionPlayerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  rawScore?: Prisma.SortOrder
  placement?: Prisma.SortOrder
  pointsAwarded?: Prisma.SortOrder
}

export type SessionPlayerSumOrderByAggregateInput = {
  rawScore?: Prisma.SortOrder
  placement?: Prisma.SortOrder
  pointsAwarded?: Prisma.SortOrder
}

export type SessionPlayerCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.SessionPlayerCreateWithoutUserInput, Prisma.SessionPlayerUncheckedCreateWithoutUserInput> | Prisma.SessionPlayerCreateWithoutUserInput[] | Prisma.SessionPlayerUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SessionPlayerCreateOrConnectWithoutUserInput | Prisma.SessionPlayerCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.SessionPlayerCreateManyUserInputEnvelope
  connect?: Prisma.SessionPlayerWhereUniqueInput | Prisma.SessionPlayerWhereUniqueInput[]
}

export type SessionPlayerUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.SessionPlayerCreateWithoutUserInput, Prisma.SessionPlayerUncheckedCreateWithoutUserInput> | Prisma.SessionPlayerCreateWithoutUserInput[] | Prisma.SessionPlayerUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SessionPlayerCreateOrConnectWithoutUserInput | Prisma.SessionPlayerCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.SessionPlayerCreateManyUserInputEnvelope
  connect?: Prisma.SessionPlayerWhereUniqueInput | Prisma.SessionPlayerWhereUniqueInput[]
}

export type SessionPlayerUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.SessionPlayerCreateWithoutUserInput, Prisma.SessionPlayerUncheckedCreateWithoutUserInput> | Prisma.SessionPlayerCreateWithoutUserInput[] | Prisma.SessionPlayerUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SessionPlayerCreateOrConnectWithoutUserInput | Prisma.SessionPlayerCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.SessionPlayerUpsertWithWhereUniqueWithoutUserInput | Prisma.SessionPlayerUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.SessionPlayerCreateManyUserInputEnvelope
  set?: Prisma.SessionPlayerWhereUniqueInput | Prisma.SessionPlayerWhereUniqueInput[]
  disconnect?: Prisma.SessionPlayerWhereUniqueInput | Prisma.SessionPlayerWhereUniqueInput[]
  delete?: Prisma.SessionPlayerWhereUniqueInput | Prisma.SessionPlayerWhereUniqueInput[]
  connect?: Prisma.SessionPlayerWhereUniqueInput | Prisma.SessionPlayerWhereUniqueInput[]
  update?: Prisma.SessionPlayerUpdateWithWhereUniqueWithoutUserInput | Prisma.SessionPlayerUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.SessionPlayerUpdateManyWithWhereWithoutUserInput | Prisma.SessionPlayerUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.SessionPlayerScalarWhereInput | Prisma.SessionPlayerScalarWhereInput[]
}

export type SessionPlayerUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.SessionPlayerCreateWithoutUserInput, Prisma.SessionPlayerUncheckedCreateWithoutUserInput> | Prisma.SessionPlayerCreateWithoutUserInput[] | Prisma.SessionPlayerUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SessionPlayerCreateOrConnectWithoutUserInput | Prisma.SessionPlayerCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.SessionPlayerUpsertWithWhereUniqueWithoutUserInput | Prisma.SessionPlayerUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.SessionPlayerCreateManyUserInputEnvelope
  set?: Prisma.SessionPlayerWhereUniqueInput | Prisma.SessionPlayerWhereUniqueInput[]
  disconnect?: Prisma.SessionPlayerWhereUniqueInput | Prisma.SessionPlayerWhereUniqueInput[]
  delete?: Prisma.SessionPlayerWhereUniqueInput | Prisma.SessionPlayerWhereUniqueInput[]
  connect?: Prisma.SessionPlayerWhereUniqueInput | Prisma.SessionPlayerWhereUniqueInput[]
  update?: Prisma.SessionPlayerUpdateWithWhereUniqueWithoutUserInput | Prisma.SessionPlayerUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.SessionPlayerUpdateManyWithWhereWithoutUserInput | Prisma.SessionPlayerUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.SessionPlayerScalarWhereInput | Prisma.SessionPlayerScalarWhereInput[]
}

export type SessionPlayerCreateNestedManyWithoutSessionInput = {
  create?: Prisma.XOR<Prisma.SessionPlayerCreateWithoutSessionInput, Prisma.SessionPlayerUncheckedCreateWithoutSessionInput> | Prisma.SessionPlayerCreateWithoutSessionInput[] | Prisma.SessionPlayerUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.SessionPlayerCreateOrConnectWithoutSessionInput | Prisma.SessionPlayerCreateOrConnectWithoutSessionInput[]
  createMany?: Prisma.SessionPlayerCreateManySessionInputEnvelope
  connect?: Prisma.SessionPlayerWhereUniqueInput | Prisma.SessionPlayerWhereUniqueInput[]
}

export type SessionPlayerUncheckedCreateNestedManyWithoutSessionInput = {
  create?: Prisma.XOR<Prisma.SessionPlayerCreateWithoutSessionInput, Prisma.SessionPlayerUncheckedCreateWithoutSessionInput> | Prisma.SessionPlayerCreateWithoutSessionInput[] | Prisma.SessionPlayerUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.SessionPlayerCreateOrConnectWithoutSessionInput | Prisma.SessionPlayerCreateOrConnectWithoutSessionInput[]
  createMany?: Prisma.SessionPlayerCreateManySessionInputEnvelope
  connect?: Prisma.SessionPlayerWhereUniqueInput | Prisma.SessionPlayerWhereUniqueInput[]
}

export type SessionPlayerUpdateManyWithoutSessionNestedInput = {
  create?: Prisma.XOR<Prisma.SessionPlayerCreateWithoutSessionInput, Prisma.SessionPlayerUncheckedCreateWithoutSessionInput> | Prisma.SessionPlayerCreateWithoutSessionInput[] | Prisma.SessionPlayerUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.SessionPlayerCreateOrConnectWithoutSessionInput | Prisma.SessionPlayerCreateOrConnectWithoutSessionInput[]
  upsert?: Prisma.SessionPlayerUpsertWithWhereUniqueWithoutSessionInput | Prisma.SessionPlayerUpsertWithWhereUniqueWithoutSessionInput[]
  createMany?: Prisma.SessionPlayerCreateManySessionInputEnvelope
  set?: Prisma.SessionPlayerWhereUniqueInput | Prisma.SessionPlayerWhereUniqueInput[]
  disconnect?: Prisma.SessionPlayerWhereUniqueInput | Prisma.SessionPlayerWhereUniqueInput[]
  delete?: Prisma.SessionPlayerWhereUniqueInput | Prisma.SessionPlayerWhereUniqueInput[]
  connect?: Prisma.SessionPlayerWhereUniqueInput | Prisma.SessionPlayerWhereUniqueInput[]
  update?: Prisma.SessionPlayerUpdateWithWhereUniqueWithoutSessionInput | Prisma.SessionPlayerUpdateWithWhereUniqueWithoutSessionInput[]
  updateMany?: Prisma.SessionPlayerUpdateManyWithWhereWithoutSessionInput | Prisma.SessionPlayerUpdateManyWithWhereWithoutSessionInput[]
  deleteMany?: Prisma.SessionPlayerScalarWhereInput | Prisma.SessionPlayerScalarWhereInput[]
}

export type SessionPlayerUncheckedUpdateManyWithoutSessionNestedInput = {
  create?: Prisma.XOR<Prisma.SessionPlayerCreateWithoutSessionInput, Prisma.SessionPlayerUncheckedCreateWithoutSessionInput> | Prisma.SessionPlayerCreateWithoutSessionInput[] | Prisma.SessionPlayerUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.SessionPlayerCreateOrConnectWithoutSessionInput | Prisma.SessionPlayerCreateOrConnectWithoutSessionInput[]
  upsert?: Prisma.SessionPlayerUpsertWithWhereUniqueWithoutSessionInput | Prisma.SessionPlayerUpsertWithWhereUniqueWithoutSessionInput[]
  createMany?: Prisma.SessionPlayerCreateManySessionInputEnvelope
  set?: Prisma.SessionPlayerWhereUniqueInput | Prisma.SessionPlayerWhereUniqueInput[]
  disconnect?: Prisma.SessionPlayerWhereUniqueInput | Prisma.SessionPlayerWhereUniqueInput[]
  delete?: Prisma.SessionPlayerWhereUniqueInput | Prisma.SessionPlayerWhereUniqueInput[]
  connect?: Prisma.SessionPlayerWhereUniqueInput | Prisma.SessionPlayerWhereUniqueInput[]
  update?: Prisma.SessionPlayerUpdateWithWhereUniqueWithoutSessionInput | Prisma.SessionPlayerUpdateWithWhereUniqueWithoutSessionInput[]
  updateMany?: Prisma.SessionPlayerUpdateManyWithWhereWithoutSessionInput | Prisma.SessionPlayerUpdateManyWithWhereWithoutSessionInput[]
  deleteMany?: Prisma.SessionPlayerScalarWhereInput | Prisma.SessionPlayerScalarWhereInput[]
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type SessionPlayerCreateWithoutUserInput = {
  id?: string
  rawScore: number
  placement: number
  pointsAwarded: number
  scoreDetails?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  session: Prisma.SessionCreateNestedOneWithoutPlayersInput
}

export type SessionPlayerUncheckedCreateWithoutUserInput = {
  id?: string
  sessionId: string
  rawScore: number
  placement: number
  pointsAwarded: number
  scoreDetails?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type SessionPlayerCreateOrConnectWithoutUserInput = {
  where: Prisma.SessionPlayerWhereUniqueInput
  create: Prisma.XOR<Prisma.SessionPlayerCreateWithoutUserInput, Prisma.SessionPlayerUncheckedCreateWithoutUserInput>
}

export type SessionPlayerCreateManyUserInputEnvelope = {
  data: Prisma.SessionPlayerCreateManyUserInput | Prisma.SessionPlayerCreateManyUserInput[]
}

export type SessionPlayerUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.SessionPlayerWhereUniqueInput
  update: Prisma.XOR<Prisma.SessionPlayerUpdateWithoutUserInput, Prisma.SessionPlayerUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.SessionPlayerCreateWithoutUserInput, Prisma.SessionPlayerUncheckedCreateWithoutUserInput>
}

export type SessionPlayerUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.SessionPlayerWhereUniqueInput
  data: Prisma.XOR<Prisma.SessionPlayerUpdateWithoutUserInput, Prisma.SessionPlayerUncheckedUpdateWithoutUserInput>
}

export type SessionPlayerUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.SessionPlayerScalarWhereInput
  data: Prisma.XOR<Prisma.SessionPlayerUpdateManyMutationInput, Prisma.SessionPlayerUncheckedUpdateManyWithoutUserInput>
}

export type SessionPlayerScalarWhereInput = {
  AND?: Prisma.SessionPlayerScalarWhereInput | Prisma.SessionPlayerScalarWhereInput[]
  OR?: Prisma.SessionPlayerScalarWhereInput[]
  NOT?: Prisma.SessionPlayerScalarWhereInput | Prisma.SessionPlayerScalarWhereInput[]
  id?: Prisma.StringFilter<"SessionPlayer"> | string
  sessionId?: Prisma.StringFilter<"SessionPlayer"> | string
  userId?: Prisma.StringFilter<"SessionPlayer"> | string
  rawScore?: Prisma.FloatFilter<"SessionPlayer"> | number
  placement?: Prisma.IntFilter<"SessionPlayer"> | number
  pointsAwarded?: Prisma.FloatFilter<"SessionPlayer"> | number
  scoreDetails?: Prisma.JsonNullableFilter<"SessionPlayer">
}

export type SessionPlayerCreateWithoutSessionInput = {
  id?: string
  rawScore: number
  placement: number
  pointsAwarded: number
  scoreDetails?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  user: Prisma.UserCreateNestedOneWithoutSessionsInput
}

export type SessionPlayerUncheckedCreateWithoutSessionInput = {
  id?: string
  userId: string
  rawScore: number
  placement: number
  pointsAwarded: number
  scoreDetails?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type SessionPlayerCreateOrConnectWithoutSessionInput = {
  where: Prisma.SessionPlayerWhereUniqueInput
  create: Prisma.XOR<Prisma.SessionPlayerCreateWithoutSessionInput, Prisma.SessionPlayerUncheckedCreateWithoutSessionInput>
}

export type SessionPlayerCreateManySessionInputEnvelope = {
  data: Prisma.SessionPlayerCreateManySessionInput | Prisma.SessionPlayerCreateManySessionInput[]
}

export type SessionPlayerUpsertWithWhereUniqueWithoutSessionInput = {
  where: Prisma.SessionPlayerWhereUniqueInput
  update: Prisma.XOR<Prisma.SessionPlayerUpdateWithoutSessionInput, Prisma.SessionPlayerUncheckedUpdateWithoutSessionInput>
  create: Prisma.XOR<Prisma.SessionPlayerCreateWithoutSessionInput, Prisma.SessionPlayerUncheckedCreateWithoutSessionInput>
}

export type SessionPlayerUpdateWithWhereUniqueWithoutSessionInput = {
  where: Prisma.SessionPlayerWhereUniqueInput
  data: Prisma.XOR<Prisma.SessionPlayerUpdateWithoutSessionInput, Prisma.SessionPlayerUncheckedUpdateWithoutSessionInput>
}

export type SessionPlayerUpdateManyWithWhereWithoutSessionInput = {
  where: Prisma.SessionPlayerScalarWhereInput
  data: Prisma.XOR<Prisma.SessionPlayerUpdateManyMutationInput, Prisma.SessionPlayerUncheckedUpdateManyWithoutSessionInput>
}

export type SessionPlayerCreateManyUserInput = {
  id?: string
  sessionId: string
  rawScore: number
  placement: number
  pointsAwarded: number
  scoreDetails?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type SessionPlayerUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rawScore?: Prisma.FloatFieldUpdateOperationsInput | number
  placement?: Prisma.IntFieldUpdateOperationsInput | number
  pointsAwarded?: Prisma.FloatFieldUpdateOperationsInput | number
  scoreDetails?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  session?: Prisma.SessionUpdateOneRequiredWithoutPlayersNestedInput
}

export type SessionPlayerUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  rawScore?: Prisma.FloatFieldUpdateOperationsInput | number
  placement?: Prisma.IntFieldUpdateOperationsInput | number
  pointsAwarded?: Prisma.FloatFieldUpdateOperationsInput | number
  scoreDetails?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type SessionPlayerUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  rawScore?: Prisma.FloatFieldUpdateOperationsInput | number
  placement?: Prisma.IntFieldUpdateOperationsInput | number
  pointsAwarded?: Prisma.FloatFieldUpdateOperationsInput | number
  scoreDetails?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type SessionPlayerCreateManySessionInput = {
  id?: string
  userId: string
  rawScore: number
  placement: number
  pointsAwarded: number
  scoreDetails?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type SessionPlayerUpdateWithoutSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rawScore?: Prisma.FloatFieldUpdateOperationsInput | number
  placement?: Prisma.IntFieldUpdateOperationsInput | number
  pointsAwarded?: Prisma.FloatFieldUpdateOperationsInput | number
  scoreDetails?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  user?: Prisma.UserUpdateOneRequiredWithoutSessionsNestedInput
}

export type SessionPlayerUncheckedUpdateWithoutSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  rawScore?: Prisma.FloatFieldUpdateOperationsInput | number
  placement?: Prisma.IntFieldUpdateOperationsInput | number
  pointsAwarded?: Prisma.FloatFieldUpdateOperationsInput | number
  scoreDetails?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type SessionPlayerUncheckedUpdateManyWithoutSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  rawScore?: Prisma.FloatFieldUpdateOperationsInput | number
  placement?: Prisma.IntFieldUpdateOperationsInput | number
  pointsAwarded?: Prisma.FloatFieldUpdateOperationsInput | number
  scoreDetails?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}



export type SessionPlayerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  userId?: boolean
  rawScore?: boolean
  placement?: boolean
  pointsAwarded?: boolean
  scoreDetails?: boolean
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sessionPlayer"]>

export type SessionPlayerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  userId?: boolean
  rawScore?: boolean
  placement?: boolean
  pointsAwarded?: boolean
  scoreDetails?: boolean
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sessionPlayer"]>

export type SessionPlayerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  userId?: boolean
  rawScore?: boolean
  placement?: boolean
  pointsAwarded?: boolean
  scoreDetails?: boolean
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sessionPlayer"]>

export type SessionPlayerSelectScalar = {
  id?: boolean
  sessionId?: boolean
  userId?: boolean
  rawScore?: boolean
  placement?: boolean
  pointsAwarded?: boolean
  scoreDetails?: boolean
}

export type SessionPlayerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "sessionId" | "userId" | "rawScore" | "placement" | "pointsAwarded" | "scoreDetails", ExtArgs["result"]["sessionPlayer"]>
export type SessionPlayerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type SessionPlayerIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type SessionPlayerIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $SessionPlayerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SessionPlayer"
  objects: {
    session: Prisma.$SessionPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    sessionId: string
    userId: string
    rawScore: number
    placement: number
    pointsAwarded: number
    scoreDetails: runtime.JsonValue | null
  }, ExtArgs["result"]["sessionPlayer"]>
  composites: {}
}

export type SessionPlayerGetPayload<S extends boolean | null | undefined | SessionPlayerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SessionPlayerPayload, S>

export type SessionPlayerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SessionPlayerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SessionPlayerCountAggregateInputType | true
  }

export interface SessionPlayerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SessionPlayer'], meta: { name: 'SessionPlayer' } }
  /**
   * Find zero or one SessionPlayer that matches the filter.
   * @param {SessionPlayerFindUniqueArgs} args - Arguments to find a SessionPlayer
   * @example
   * // Get one SessionPlayer
   * const sessionPlayer = await prisma.sessionPlayer.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SessionPlayerFindUniqueArgs>(args: Prisma.SelectSubset<T, SessionPlayerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SessionPlayerClient<runtime.Types.Result.GetResult<Prisma.$SessionPlayerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SessionPlayer that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SessionPlayerFindUniqueOrThrowArgs} args - Arguments to find a SessionPlayer
   * @example
   * // Get one SessionPlayer
   * const sessionPlayer = await prisma.sessionPlayer.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SessionPlayerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SessionPlayerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SessionPlayerClient<runtime.Types.Result.GetResult<Prisma.$SessionPlayerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SessionPlayer that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionPlayerFindFirstArgs} args - Arguments to find a SessionPlayer
   * @example
   * // Get one SessionPlayer
   * const sessionPlayer = await prisma.sessionPlayer.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SessionPlayerFindFirstArgs>(args?: Prisma.SelectSubset<T, SessionPlayerFindFirstArgs<ExtArgs>>): Prisma.Prisma__SessionPlayerClient<runtime.Types.Result.GetResult<Prisma.$SessionPlayerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SessionPlayer that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionPlayerFindFirstOrThrowArgs} args - Arguments to find a SessionPlayer
   * @example
   * // Get one SessionPlayer
   * const sessionPlayer = await prisma.sessionPlayer.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SessionPlayerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SessionPlayerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SessionPlayerClient<runtime.Types.Result.GetResult<Prisma.$SessionPlayerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SessionPlayers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionPlayerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SessionPlayers
   * const sessionPlayers = await prisma.sessionPlayer.findMany()
   * 
   * // Get first 10 SessionPlayers
   * const sessionPlayers = await prisma.sessionPlayer.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const sessionPlayerWithIdOnly = await prisma.sessionPlayer.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SessionPlayerFindManyArgs>(args?: Prisma.SelectSubset<T, SessionPlayerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionPlayerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SessionPlayer.
   * @param {SessionPlayerCreateArgs} args - Arguments to create a SessionPlayer.
   * @example
   * // Create one SessionPlayer
   * const SessionPlayer = await prisma.sessionPlayer.create({
   *   data: {
   *     // ... data to create a SessionPlayer
   *   }
   * })
   * 
   */
  create<T extends SessionPlayerCreateArgs>(args: Prisma.SelectSubset<T, SessionPlayerCreateArgs<ExtArgs>>): Prisma.Prisma__SessionPlayerClient<runtime.Types.Result.GetResult<Prisma.$SessionPlayerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SessionPlayers.
   * @param {SessionPlayerCreateManyArgs} args - Arguments to create many SessionPlayers.
   * @example
   * // Create many SessionPlayers
   * const sessionPlayer = await prisma.sessionPlayer.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SessionPlayerCreateManyArgs>(args?: Prisma.SelectSubset<T, SessionPlayerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SessionPlayers and returns the data saved in the database.
   * @param {SessionPlayerCreateManyAndReturnArgs} args - Arguments to create many SessionPlayers.
   * @example
   * // Create many SessionPlayers
   * const sessionPlayer = await prisma.sessionPlayer.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SessionPlayers and only return the `id`
   * const sessionPlayerWithIdOnly = await prisma.sessionPlayer.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SessionPlayerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SessionPlayerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionPlayerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SessionPlayer.
   * @param {SessionPlayerDeleteArgs} args - Arguments to delete one SessionPlayer.
   * @example
   * // Delete one SessionPlayer
   * const SessionPlayer = await prisma.sessionPlayer.delete({
   *   where: {
   *     // ... filter to delete one SessionPlayer
   *   }
   * })
   * 
   */
  delete<T extends SessionPlayerDeleteArgs>(args: Prisma.SelectSubset<T, SessionPlayerDeleteArgs<ExtArgs>>): Prisma.Prisma__SessionPlayerClient<runtime.Types.Result.GetResult<Prisma.$SessionPlayerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SessionPlayer.
   * @param {SessionPlayerUpdateArgs} args - Arguments to update one SessionPlayer.
   * @example
   * // Update one SessionPlayer
   * const sessionPlayer = await prisma.sessionPlayer.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SessionPlayerUpdateArgs>(args: Prisma.SelectSubset<T, SessionPlayerUpdateArgs<ExtArgs>>): Prisma.Prisma__SessionPlayerClient<runtime.Types.Result.GetResult<Prisma.$SessionPlayerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SessionPlayers.
   * @param {SessionPlayerDeleteManyArgs} args - Arguments to filter SessionPlayers to delete.
   * @example
   * // Delete a few SessionPlayers
   * const { count } = await prisma.sessionPlayer.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SessionPlayerDeleteManyArgs>(args?: Prisma.SelectSubset<T, SessionPlayerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SessionPlayers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionPlayerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SessionPlayers
   * const sessionPlayer = await prisma.sessionPlayer.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SessionPlayerUpdateManyArgs>(args: Prisma.SelectSubset<T, SessionPlayerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SessionPlayers and returns the data updated in the database.
   * @param {SessionPlayerUpdateManyAndReturnArgs} args - Arguments to update many SessionPlayers.
   * @example
   * // Update many SessionPlayers
   * const sessionPlayer = await prisma.sessionPlayer.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SessionPlayers and only return the `id`
   * const sessionPlayerWithIdOnly = await prisma.sessionPlayer.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SessionPlayerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SessionPlayerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionPlayerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SessionPlayer.
   * @param {SessionPlayerUpsertArgs} args - Arguments to update or create a SessionPlayer.
   * @example
   * // Update or create a SessionPlayer
   * const sessionPlayer = await prisma.sessionPlayer.upsert({
   *   create: {
   *     // ... data to create a SessionPlayer
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SessionPlayer we want to update
   *   }
   * })
   */
  upsert<T extends SessionPlayerUpsertArgs>(args: Prisma.SelectSubset<T, SessionPlayerUpsertArgs<ExtArgs>>): Prisma.Prisma__SessionPlayerClient<runtime.Types.Result.GetResult<Prisma.$SessionPlayerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SessionPlayers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionPlayerCountArgs} args - Arguments to filter SessionPlayers to count.
   * @example
   * // Count the number of SessionPlayers
   * const count = await prisma.sessionPlayer.count({
   *   where: {
   *     // ... the filter for the SessionPlayers we want to count
   *   }
   * })
  **/
  count<T extends SessionPlayerCountArgs>(
    args?: Prisma.Subset<T, SessionPlayerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SessionPlayerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SessionPlayer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionPlayerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SessionPlayerAggregateArgs>(args: Prisma.Subset<T, SessionPlayerAggregateArgs>): Prisma.PrismaPromise<GetSessionPlayerAggregateType<T>>

  /**
   * Group by SessionPlayer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionPlayerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SessionPlayerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SessionPlayerGroupByArgs['orderBy'] }
      : { orderBy?: SessionPlayerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SessionPlayerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSessionPlayerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SessionPlayer model
 */
readonly fields: SessionPlayerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SessionPlayer.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SessionPlayerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  session<T extends Prisma.SessionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SessionDefaultArgs<ExtArgs>>): Prisma.Prisma__SessionClient<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SessionPlayer model
 */
export interface SessionPlayerFieldRefs {
  readonly id: Prisma.FieldRef<"SessionPlayer", 'String'>
  readonly sessionId: Prisma.FieldRef<"SessionPlayer", 'String'>
  readonly userId: Prisma.FieldRef<"SessionPlayer", 'String'>
  readonly rawScore: Prisma.FieldRef<"SessionPlayer", 'Float'>
  readonly placement: Prisma.FieldRef<"SessionPlayer", 'Int'>
  readonly pointsAwarded: Prisma.FieldRef<"SessionPlayer", 'Float'>
  readonly scoreDetails: Prisma.FieldRef<"SessionPlayer", 'Json'>
}
    

// Custom InputTypes
/**
 * SessionPlayer findUnique
 */
export type SessionPlayerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPlayer
   */
  select?: Prisma.SessionPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPlayer
   */
  omit?: Prisma.SessionPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionPlayerInclude<ExtArgs> | null
  /**
   * Filter, which SessionPlayer to fetch.
   */
  where: Prisma.SessionPlayerWhereUniqueInput
}

/**
 * SessionPlayer findUniqueOrThrow
 */
export type SessionPlayerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPlayer
   */
  select?: Prisma.SessionPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPlayer
   */
  omit?: Prisma.SessionPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionPlayerInclude<ExtArgs> | null
  /**
   * Filter, which SessionPlayer to fetch.
   */
  where: Prisma.SessionPlayerWhereUniqueInput
}

/**
 * SessionPlayer findFirst
 */
export type SessionPlayerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPlayer
   */
  select?: Prisma.SessionPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPlayer
   */
  omit?: Prisma.SessionPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionPlayerInclude<ExtArgs> | null
  /**
   * Filter, which SessionPlayer to fetch.
   */
  where?: Prisma.SessionPlayerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SessionPlayers to fetch.
   */
  orderBy?: Prisma.SessionPlayerOrderByWithRelationInput | Prisma.SessionPlayerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SessionPlayers.
   */
  cursor?: Prisma.SessionPlayerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SessionPlayers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SessionPlayers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SessionPlayers.
   */
  distinct?: Prisma.SessionPlayerScalarFieldEnum | Prisma.SessionPlayerScalarFieldEnum[]
}

/**
 * SessionPlayer findFirstOrThrow
 */
export type SessionPlayerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPlayer
   */
  select?: Prisma.SessionPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPlayer
   */
  omit?: Prisma.SessionPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionPlayerInclude<ExtArgs> | null
  /**
   * Filter, which SessionPlayer to fetch.
   */
  where?: Prisma.SessionPlayerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SessionPlayers to fetch.
   */
  orderBy?: Prisma.SessionPlayerOrderByWithRelationInput | Prisma.SessionPlayerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SessionPlayers.
   */
  cursor?: Prisma.SessionPlayerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SessionPlayers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SessionPlayers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SessionPlayers.
   */
  distinct?: Prisma.SessionPlayerScalarFieldEnum | Prisma.SessionPlayerScalarFieldEnum[]
}

/**
 * SessionPlayer findMany
 */
export type SessionPlayerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPlayer
   */
  select?: Prisma.SessionPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPlayer
   */
  omit?: Prisma.SessionPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionPlayerInclude<ExtArgs> | null
  /**
   * Filter, which SessionPlayers to fetch.
   */
  where?: Prisma.SessionPlayerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SessionPlayers to fetch.
   */
  orderBy?: Prisma.SessionPlayerOrderByWithRelationInput | Prisma.SessionPlayerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SessionPlayers.
   */
  cursor?: Prisma.SessionPlayerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SessionPlayers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SessionPlayers.
   */
  skip?: number
  distinct?: Prisma.SessionPlayerScalarFieldEnum | Prisma.SessionPlayerScalarFieldEnum[]
}

/**
 * SessionPlayer create
 */
export type SessionPlayerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPlayer
   */
  select?: Prisma.SessionPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPlayer
   */
  omit?: Prisma.SessionPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionPlayerInclude<ExtArgs> | null
  /**
   * The data needed to create a SessionPlayer.
   */
  data: Prisma.XOR<Prisma.SessionPlayerCreateInput, Prisma.SessionPlayerUncheckedCreateInput>
}

/**
 * SessionPlayer createMany
 */
export type SessionPlayerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SessionPlayers.
   */
  data: Prisma.SessionPlayerCreateManyInput | Prisma.SessionPlayerCreateManyInput[]
}

/**
 * SessionPlayer createManyAndReturn
 */
export type SessionPlayerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPlayer
   */
  select?: Prisma.SessionPlayerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPlayer
   */
  omit?: Prisma.SessionPlayerOmit<ExtArgs> | null
  /**
   * The data used to create many SessionPlayers.
   */
  data: Prisma.SessionPlayerCreateManyInput | Prisma.SessionPlayerCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionPlayerIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SessionPlayer update
 */
export type SessionPlayerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPlayer
   */
  select?: Prisma.SessionPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPlayer
   */
  omit?: Prisma.SessionPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionPlayerInclude<ExtArgs> | null
  /**
   * The data needed to update a SessionPlayer.
   */
  data: Prisma.XOR<Prisma.SessionPlayerUpdateInput, Prisma.SessionPlayerUncheckedUpdateInput>
  /**
   * Choose, which SessionPlayer to update.
   */
  where: Prisma.SessionPlayerWhereUniqueInput
}

/**
 * SessionPlayer updateMany
 */
export type SessionPlayerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SessionPlayers.
   */
  data: Prisma.XOR<Prisma.SessionPlayerUpdateManyMutationInput, Prisma.SessionPlayerUncheckedUpdateManyInput>
  /**
   * Filter which SessionPlayers to update
   */
  where?: Prisma.SessionPlayerWhereInput
  /**
   * Limit how many SessionPlayers to update.
   */
  limit?: number
}

/**
 * SessionPlayer updateManyAndReturn
 */
export type SessionPlayerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPlayer
   */
  select?: Prisma.SessionPlayerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPlayer
   */
  omit?: Prisma.SessionPlayerOmit<ExtArgs> | null
  /**
   * The data used to update SessionPlayers.
   */
  data: Prisma.XOR<Prisma.SessionPlayerUpdateManyMutationInput, Prisma.SessionPlayerUncheckedUpdateManyInput>
  /**
   * Filter which SessionPlayers to update
   */
  where?: Prisma.SessionPlayerWhereInput
  /**
   * Limit how many SessionPlayers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionPlayerIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SessionPlayer upsert
 */
export type SessionPlayerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPlayer
   */
  select?: Prisma.SessionPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPlayer
   */
  omit?: Prisma.SessionPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionPlayerInclude<ExtArgs> | null
  /**
   * The filter to search for the SessionPlayer to update in case it exists.
   */
  where: Prisma.SessionPlayerWhereUniqueInput
  /**
   * In case the SessionPlayer found by the `where` argument doesn't exist, create a new SessionPlayer with this data.
   */
  create: Prisma.XOR<Prisma.SessionPlayerCreateInput, Prisma.SessionPlayerUncheckedCreateInput>
  /**
   * In case the SessionPlayer was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SessionPlayerUpdateInput, Prisma.SessionPlayerUncheckedUpdateInput>
}

/**
 * SessionPlayer delete
 */
export type SessionPlayerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPlayer
   */
  select?: Prisma.SessionPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPlayer
   */
  omit?: Prisma.SessionPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionPlayerInclude<ExtArgs> | null
  /**
   * Filter which SessionPlayer to delete.
   */
  where: Prisma.SessionPlayerWhereUniqueInput
}

/**
 * SessionPlayer deleteMany
 */
export type SessionPlayerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SessionPlayers to delete
   */
  where?: Prisma.SessionPlayerWhereInput
  /**
   * Limit how many SessionPlayers to delete.
   */
  limit?: number
}

/**
 * SessionPlayer without action
 */
export type SessionPlayerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPlayer
   */
  select?: Prisma.SessionPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPlayer
   */
  omit?: Prisma.SessionPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionPlayerInclude<ExtArgs> | null
}
